### ISSUE TITLE
Error  Invalid category

### ISSUE THREAD

**Issue by jsstelt** [beamtic/php-photo-gallery#5]
I am getting this error if I use numbers in the gallery name folders. 
Any easy fix?

**Comment by saudiqbal** [comment]
Replace preg_match("/^[a-zæøåÆØÅ-]+$/i"
with
preg_match("/^[a-zA-Z0-9-]/"

**Comment by jacobseated** [comment]
I'll look into it after work. Thanks.

**Comment by jacobseated** [comment]
Fixed.
