### ISSUE TITLE
 PHP Error:  unexpected '=' in wink.ini  in \webroot\footer.php on line 3

### ISSUE THREAD

**Issue by bakertaylor28** [beamtic/php-photo-gallery#8]
Current Release of XAMPP throws the following error:
 PHP Error:  unexpected '=' in wink.ini  in \webroot\footer.php on line 3

**Comment by jacobseated** [comment]
This is related to XAMPP or your particular configuration. I don't use XAMPP and don't recommend it. The project does not even have a `footer.php`.
